[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = ["npm install -g pnpm@10.26.1", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "BASE_PATH=/ PORT=3000 pnpm --filter @workspace/tg-miniapp run build",
  "pnpm --filter @workspace/api-server run build"
]

[start]
cmd = "node --enable-source-maps artifacts/api-server/dist/index.mjs"
